### ISSUE TITLE
When joining to server player's name is being set to null

### ISSUE THREAD

**Issue by gilvex** [MrAfitol/RPName#1]
![image](https://user-images.githubusercontent.com/50551032/213529851-eda5689b-8b1c-4411-b9b3-8d9d915b5eed.png)
![image](https://user-images.githubusercontent.com/50551032/213529783-1941ef90-0d6a-46b0-a2a6-01a8c1a29dfc.png)

**Comment by MrAfitol** [comment]
Check out the new version [1.0.5](https://github.com/MrAfitol/RPName/releases/tag/1.0.5)
